# Config file for the SocialTap app

defaults: &defaults
    Elasticsearch:
        hostname: localhost
        port: 9200
    rabbitmq:
        host: 127.0.0.1
    Gnip:
        account_name: YOUR GNIP ACCOUNT NAME
        username: YOUR GNIP USERNAME
        password: YOUR GNIP PASSWORD
    reports:
        output_directory: PATH TO DIRECTORY TO GENERATE REPORT FILES IN
    Twitter:
        consumer_key: TWITTER CONSUMER KEY
        consumer_secret: TWITTER CONSUMER SECRET
    Sentiment140:
        app_id: YOUR SENTIMENT140 APP ID
    Analysis:
        default_workers: 4
        job_mananger_hostname: localhost
        sentiment140analyzer:
            workers: 1

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults
