# Config file for the SocialTap app

defaults: &defaults
    Elasticsearch:
        hostname: localhost
        port: 9200
    Gnip:
        powertrack_stream_url: YOUR STREAM URL
        powertrack_rules_url: YOUR RULES URL
        username: YOUR GNIP USERNAME
        password: YOUR GNIP PASSWORD
    data_files:
        import_directory: PATH TO DIRECTORY CONTAINING DATA FILES TO IMPORT
    Twitter:
        consumer_key: TWITTER CONSUMER KEY
        consumer_secret: TWITTER CONSUMER SECRET
    Sentiment140:
        app_id: YOUR SENTIMENT140 APP ID

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults
