#!/usr/bin/env ruby

require 'fileutils'
require 'socket'

def run!

	if ARGV.count < 1
		$stderr.puts "Usage: import_worker.rb type"
		exit(false)
	end
	type = ARGV[0]

	# Allow running in foreground for debugging, but log output by default.
	unless ARGV[1] == "debug"
		log_directory = File.join(File.dirname(__FILE__), "../../../log/import/#{type}")
		FileUtils.mkdir_p(log_directory) unless File.exist?(log_directory)
		$stdout.reopen(File.join(log_directory, "#{Socket.gethostname}-#{Process.pid}.log"), "w")
		$stderr.reopen(File.join(log_directory, "#{Socket.gethostname}-#{Process.pid}.err"), "w")
	end

	# Load Rails environment
	require "#{File.expand_path(File.dirname(__FILE__))}/../../../config/environment"

	manager = Import::WorkerManager.instance

	if manager.all_worker_processes.select { |p| p[:type] == 'gnip'} .count > 0
		puts "[#{DateTime.now}] Unable to run multiple Gnip import workers."
		puts "[#{DateTime.now}] Aborting"
		exit(false)
	end

	# Store worker PID and type
	File.open(manager.pid_file(Process.pid), "w") do |f|
		f.puts type
	end

	worker_class = Object.const_get("Import::Worker::#{type.capitalize}Worker")
	worker = worker_class.new

	stop_queue = Queue.new

	# worker.shutdown cannot be called from a signal trap context. So instead, have the signal
	# handlers notify a background thread to call shutdown.

	Thread.new do
		stop_queue.pop # Blocks until an interrupt signal is received.
		worker.shutdown
		File.delete(manager.pid_file(Process.pid))
	end

	["HUP", "INT", "TERM"].each do |signal|
		Signal.trap(signal) {
			puts "[#{DateTime.now}] Received #{signal} signal"
			stop_queue.push(true)
		}
	end

	worker.startup

end

run! if __FILE__ == $0

